name: firealert_flutter
description: FireAlert - Yangın Erken Uyarı Sistemi (Flutter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  go_router: ^12.1.3
  
  # Backend & API
  supabase_flutter: ^2.3.4
  http: ^1.1.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  
  # Storage & Offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Media & Permissions
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  camera: ^0.10.5+9
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  
  # State Management & Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
